-- ============================================================
-- Jarvis OS — Phase 2 Schema
-- ============================================================

-- Daily composite scores
create table if not exists public.daily_scores (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid references auth.users(id) on delete cascade,
  date              date not null,
  total_score       integer not null check (total_score >= 0 and total_score <= 100),
  recovery_score    integer check (recovery_score >= 0 and recovery_score <= 100),
  nutrition_score   integer check (nutrition_score >= 0 and nutrition_score <= 100),
  training_score    integer check (training_score >= 0 and training_score <= 100),
  screen_time_score integer check (screen_time_score >= 0 and screen_time_score <= 100),
  business_score    integer check (business_score >= 0 and business_score <= 100),
  sleep_score       integer check (sleep_score >= 0 and sleep_score <= 100),
  raw_inputs        jsonb,
  created_at        timestamptz not null default now(),
  unique (user_id, date)
);

-- Workout sessions
create table if not exists public.workouts (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid references auth.users(id) on delete cascade,
  date        date not null default current_date,
  type        text not null check (type in ('upper', 'explosive', 'lower', 'custom')),
  notes       text,
  duration    integer,   -- minutes
  created_at  timestamptz not null default now()
);

-- Individual sets within a workout
create table if not exists public.workout_sets (
  id          uuid primary key default gen_random_uuid(),
  workout_id  uuid not null references public.workouts(id) on delete cascade,
  exercise    text not null,
  set_number  integer not null,
  weight      text,          -- stored as text to handle "BW", "BW+50", "185lb"
  weight_lbs  numeric,       -- numeric for PR comparisons
  reps        integer,
  rpe         numeric,
  is_top_set  boolean default false,
  created_at  timestamptz not null default now()
);

-- Personal records
create table if not exists public.personal_records (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid references auth.users(id) on delete cascade,
  exercise       text not null,
  value          numeric,
  unit           text not null check (unit in ('lb', 'inches', 'bodyweight', '+lb')),
  date_achieved  date,
  previous_value numeric,
  notes          text,
  created_at     timestamptz not null default now(),
  unique (user_id, exercise)
);

-- Body metrics (weight + body fat)
create table if not exists public.body_metrics (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid references auth.users(id) on delete cascade,
  date         date not null,
  weight_lbs   numeric not null,
  body_fat_pct numeric,
  created_at   timestamptz not null default now(),
  unique (user_id, date)
);

-- Pattern / insight records (generated by nightly job)
create table if not exists public.patterns (
  id                 uuid primary key default gen_random_uuid(),
  user_id            uuid references auth.users(id) on delete cascade,
  generated_at       timestamptz not null default now(),
  insight_text       text not null,
  confidence_pct     integer check (confidence_pct >= 0 and confidence_pct <= 100),
  days_observed      integer,
  category           text check (category in ('recovery', 'training', 'business', 'habits')),
  recommended_action text,
  trend              text check (trend in ('positive', 'negative', 'neutral')),
  raw_correlation    jsonb
);

-- ============================================================
-- Row Level Security
-- ============================================================

alter table public.daily_scores enable row level security;
alter table public.workouts enable row level security;
alter table public.workout_sets enable row level security;
alter table public.personal_records enable row level security;
alter table public.body_metrics enable row level security;
alter table public.patterns enable row level security;

create policy "daily_scores: owner" on public.daily_scores for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "workouts: owner" on public.workouts for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "workout_sets: owner via workout" on public.workout_sets for all
  using (exists (select 1 from public.workouts w where w.id = workout_sets.workout_id and w.user_id = auth.uid()));

create policy "personal_records: owner" on public.personal_records for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "body_metrics: owner" on public.body_metrics for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "patterns: owner" on public.patterns for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ============================================================
-- Indexes
-- ============================================================

create index if not exists daily_scores_date_idx on public.daily_scores(user_id, date desc);
create index if not exists workouts_date_idx on public.workouts(user_id, date desc);
create index if not exists workout_sets_workout_idx on public.workout_sets(workout_id);
create index if not exists body_metrics_date_idx on public.body_metrics(user_id, date desc);
create index if not exists patterns_generated_idx on public.patterns(user_id, generated_at desc);

-- ============================================================
-- Seed PRs for new users via trigger (extend existing trigger)
-- ============================================================

create or replace function public.seed_user_performance_data()
returns trigger language plpgsql security definer as $$
begin
  insert into public.personal_records (user_id, exercise, value, unit, date_achieved, previous_value, notes)
  values
    (new.id, 'Standing Vert', 28, 'inches', '2024-01-01', null, 'Baseline'),
    (new.id, 'Approach Vert', 34.1, 'inches', '2025-03-15', 31.5, null),
    (new.id, 'Standing Reach', 86.5, 'inches', '2024-06-01', null, '7''2.5"'),
    (new.id, 'Power Clean', 185, 'lb', '2025-02-10', 175, null),
    (new.id, 'Bench Press', 230, 'lb', '2025-01-22', 215, null),
    (new.id, 'Front Squat', 225, 'lb', '2025-04-03', 205, null),
    (new.id, 'Back Squat', 275, 'lb', '2025-03-28', 255, null),
    (new.id, 'Conv. Deadlift', 335, 'lb', '2025-04-15', 315, null),
    (new.id, 'Weighted Pull-up', 50, '+lb', '2025-02-28', 40, null),
    (new.id, 'Trap Bar Jump Squat', 145, 'lb', '2025-05-01', 135, null),
    (new.id, 'Leg Extension', 260, 'lb', '2025-04-20', 245, null),
    (new.id, 'Muscle Up', null, 'bodyweight', '2024-11-01', null, null),
    (new.id, 'Shoulder Press Machine', null, 'lb', null, null, null),
    (new.id, 'RDL', null, 'lb', null, null, null),
    (new.id, 'Seated Calf Raise', null, 'lb', null, null, null);
  return new;
end;
$$;

create trigger on_auth_user_created_performance
  after insert on auth.users
  for each row execute procedure public.seed_user_performance_data();
